#if !canImport(ObjectiveC)
import XCTest

extension Base32Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Base32Tests = [
        ("testDecodeBase32", testDecodeBase32),
        ("testDecodeIncorrectLength", testDecodeIncorrectLength),
        ("testDecodeInvalidCharacter", testDecodeInvalidCharacter),
        ("testDecodePadding", testDecodePadding),
        ("testDecodeTable", testDecodeTable),
        ("testEncode1", testEncode1),
        ("testEncode2", testEncode2),
        ("testEncode3", testEncode3),
        ("testEncode4", testEncode4),
        ("testEncode5", testEncode5),
        ("testEncode6", testEncode6),
        ("testEncode7", testEncode7),
        ("testEncode8", testEncode8),
        ("testEncodeBase32", testEncodeBase32),
        ("testEncodeNoPad", testEncodeNoPad),
        ("testEncodePad1", testEncodePad1),
        ("testEncodePad2", testEncodePad2),
        ("testEncodePad3", testEncodePad3),
        ("testEncodePad4", testEncodePad4),
    ]
}

extension ULIDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ULIDTests = [
        ("testComparable1", testComparable1),
        ("testComparable2", testComparable2),
        ("testComparable3", testComparable3),
        ("testComparable4", testComparable4),
        ("testCustomStringConvertible", testCustomStringConvertible),
        ("testDecodable", testDecodable),
        ("testDecodableError", testDecodableError),
        ("testEncodable", testEncodable),
        ("testEquatable1", testEquatable1),
        ("testEquatable2", testEquatable2),
        ("testGenerateRandomness", testGenerateRandomness),
        ("testGenerateTimestamp", testGenerateTimestamp),
        ("testHashable1", testHashable1),
        ("testHashable2", testHashable2),
        ("testHashable3", testHashable3),
        ("testMemorySize", testMemorySize),
        ("testParseULIDData", testParseULIDData),
        ("testParseULIDDataError", testParseULIDDataError),
        ("testParseULIDString", testParseULIDString),
        ("testParseULIDStringError", testParseULIDStringError),
        ("testULIDDataLength", testULIDDataLength),
        ("testULIDStringLength", testULIDStringLength),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Base32Tests.__allTests__Base32Tests),
        testCase(ULIDTests.__allTests__ULIDTests),
    ]
}
#endif
