name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-macos:
    strategy:
      matrix:
        xcode-version: ['26.5', '26.3']
    runs-on: macos-26
    timeout-minutes: 5
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
    steps:
      - uses: actions/checkout@v6
      - name: Run swift test
        run: swift test

  test-on-linux:
    strategy:
      matrix:
        swift-version: ['6.3', '6.2', '6.1', '6.0']
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libcurl4-openssl-dev
      - name: Install Swift ${{ matrix.swift-version }}
        run: >
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz &&
          tar zxf swiftly-$(uname -m).tar.gz &&
          ./swiftly init --assume-yes --skip-install &&
          . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh" &&
          swiftly install --use ${{ matrix.swift-version }}
      - name: Run swift test
        run: |
          . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh"
          swift --version
          swift test
